plugin_format_version: 2
name: admin-ui-sound
namespace: official
version: 1.0.0-1
author: Wazo Team
display_name: Wazo Sound Files
min_wazo_version: 18.02
tags:
  - application
  - sound
homepage: https://github.com/wazo-pbx/wazo-admin-ui-sound
